/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export const HeadersSchema = {
  title: "Headers Schema",
  type: "object",
  properties: {
    "h-Custom": { type: "string" },
  },
  additionalProperties: false,
  required: ["h-Custom"],
} as const;
