/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export const QuerystringSchema = {
  title: "Querystring Schema",
  type: "object",
  properties: {
    username: { type: "string" },
    password: { type: "string" },
  },
  additionalProperties: false,
  required: ["username", "password"],
} as const;
